### ISSUE TITLE
[Suggestion] EssentialsX GUI (Addon)

### ISSUE THREAD

**Issue by instantout** [promcteam/BossShopPro#104]
[https://www.spigotmc.org/resources/essentialsgui-bsp-playerfriendly-essentials-warp-and-kit-gui.34023/](url)

So, BSP originally Created Essentials (at the time) Gui Addon. I was able to configure/figure it out long time ago. The default was nice.
but you could change the icon, at kit.yml of Essentials, aswell as change the order at the kit.yml from Essentials. It died on (Beta).
this is better than the kit preview from essentialsX, aswell as you could add Glass planes/etc to fit in your style.
It was as advanced, as TrickyShops.

Edit: I really don't know if Genesis (itself) has this inside already. or if there is a Addon somewere in the Discord. But, would like to see it on spigotmc.org

**Comment by Travja** [comment]
That plugin was done by a different author and the source code is not available. So I can't upgrade it to work with Genesis, nor are there other alternative extensions that I know about

**Comment by materialplane** [comment]
I sent an email to the original dev of that addon, but that was several months ago. If they ever get back to me with thee source and allow us to use it we will add it.

**Comment by Travja** [comment]
Closing as not planned for now.
