### ISSUE TITLE
Breaks TrickyShops Compatability

### ISSUE THREAD

**Issue by TorbenGG** [promcteam/BossShopPro#17]
I am using TrickyShops for most of my ShopItems. And all those that use Tricky Shops are just stone while using this Version of BossShopPro instead of the Original one.

https://www.spigotmc.org/resources/trickyshops-bsp-makes-creating-shops-way-faster.26269/

**Comment by goflishMC** [comment]
> I am using TrickyShops for most of my ShopItems. And all those that use Tricky Shops are just stone while using this Version of BossShopPro instead of the Original one.
> 
> https://www.spigotmc.org/resources/trickyshops-bsp-makes-creating-shops-way-faster.26269/

that's because the only addon we have updated is BSP Items.

**Comment by lijinhong11** [comment]
Will update before Jan. 19th.

**Comment by TorbenGG** [comment]
Thank You sounds great. And thanks for the fast response :)
