### ISSUE TITLE
Shops dont open

### ISSUE THREAD

**Issue by Remski01** [promcteam/BossShopPro#23]
Shops dont open and cause an little lag on first try, after that it will just say `That shop is not existing...`

No errors on startup. 

Paper version/Plugin version: Paper-431(1.19.3)2.1.0-20221229

**Comment by Remski01** [comment]
https://postimg.cc/gLq5hng8

**Comment by Remski01** [comment]
Have both restarted and reloaded the plugin.

**Comment by Travja** [comment]
Have you tried this any time recently?
