### ISSUE TITLE
功能的缺失，请恢复一些功能，比如cooldown

### ISSUE THREAD

**Issue by VIQingNiao** [promcteam/BossShopPro#32]
Condition:
      - type:cooldown
      - over:20

cooldown已经不能使用了，设置好像出现了错误，我希望得到 如何给获得物品添加冷却时间的办法。另外就是

ShopName: 建筑主菜单
DisplayName: '&eyungames'
signs:
  text: '[建筑主菜单]'
  NeedPermissionToCreateSign: false
shop:

[15:15:30 INFO]: Starting BossShop reload...
[15:15:30 INFO]: [BossShopPro] Hooked into PlaceholderAPI.
[15:15:30 ERROR]: [BossShopPro] Unable to add condition 'over:20' to shopitem 'book'! You need to define a conditiontype before you start listing conditions! [Shop: 建筑主菜单]
[15:15:30 INFO]: [BossShopPro] Loaded 14 Shops!
[15:15:30 INFO]: [BossShopPro] Vault found.

**Comment by Travja** [comment]
Please use English if you can. Our developers all speak English, so that'll make things a little easier on all of us

**Comment by VIQingNiao** [comment]
Condition:
  - type:cooldown
  - over:20

This doesn't work, what should I do?Time delay function

**Comment by goflishMC** [comment]
cooldown is not a type

The available types are here: https://promcteam.com/wiki/index.php/BossShopPro:Conditions#Available_condition_types

Can you explain what you are wanting to do, so we can better help you?

**Comment by VIQingNiao** [comment]
Add an interval time to the command, which is the cooldown time

**Comment by VIQingNiao** [comment]
For example, if I want to get an apple, I can give it one click, but it takes 30 seconds to order it again

**Comment by goflishMC** [comment]
<pre>Condition:
  - type:RealSecond
  - over:30</pre>

can you try this?

**Comment by VIQingNiao** [comment]
It's invalid, the item has disappeared from my menu

**Comment by goflishMC** [comment]
Does the item show up in the menu after 30 seconds?

I just read this on the wiki, "If the conditions of a shopitem are not met the shopitem won't be displayed."

**Comment by VIQingNiao** [comment]
Condition:
  - type:RealSecond
  - over:30

After setting up, I was able to click 10 times and get the book

Then the project disappeared from the menu and has not yet appeared

**Comment by goflishMC** [comment]
What you want is this, correct?

1. You open the menu
2. Wait 30 seconds
3. Click to get the book
4. Close menu

**Comment by goflishMC** [comment]
After looking through the wiki, i don't see any options to put a cooldown like you want.

We will need to add this feature. I will put it on our to do list.

**Comment by VIQingNiao** [comment]
You open the menu
Click to get the book
Wait 30 seconds
Close menu
open the menu
Book appears in 30 seconds
Click to get the book
Wait 30 seconds
Close menu

..............

**Comment by VIQingNiao** [comment]
https://www.spigotmc.org/resources/guishopmanager-bsp-adds-new-ways-to-open-a-shop.26272/

**Comment by VIQingNiao** [comment]
I think I realize the problem, but thank you for your reply and help. I hope to add this feature as soon as possible instead of expanding it

**Comment by VIQingNiao** [comment]
I am a buyer and loyal user of this plugin. Thank you very much for bringing it back to life in a higher version and allowing more people to use it. Thank you very much!
English is not my native language, so using a translation may seem strange. I apologize for any inconvenience caused

**Comment by goflishMC** [comment]
I haven't tried that one yet. Is it working for you?

**Comment by goflishMC** [comment]
> > https://www.spigotmc.org/resources/limiteduses-bsp-allows-to-limit-the-amount-of-uses-of-shop-items.26275/
> 
> So LimitedUses has the cooldown functionality. Do you have LimitedUses installed?

I'm not sure it will work because we haven't updated that one yet

**Comment by VIQingNiao** [comment]
I am currently the latest version, and I think the plugin is outdated. We should put these features together and make it a whole

**Comment by goflishMC** [comment]
We will update that plugin soon! thanks for your feedback.

**Comment by VIQingNiao** [comment]
just installed the LimitedUses plugin and it can be used normally, but I think this should be a feature of the Bossshoppro plugin, so do you plan to integrate it in the future?

**Comment by VIQingNiao** [comment]
paper-1.20.1-96.jar
bossshoppro-2.1.0-20230422.101939-23
BSP-LimitedUses-1.1.0
