### ISSUE TITLE
[Suggestion] organize shops into folders/directories

### ISSUE THREAD

**Issue by austv** [promcteam/BossShopPro#35]
Option to shops work inside directories. Inside the "shops" folder, we could create new folders inside it and organize our shops.

for example, **container/plugins/BossShopPro/shops/stores/food.yml**

![image](https://github.com/promcteam/BossShopPro/assets/66658478/c664d32b-6f3d-42ef-b107-f5670ed1c56f)
![image](https://github.com/promcteam/BossShopPro/assets/66658478/27ff721b-bc73-43cd-9177-c711ad460b06)

> Would be great for large servers that have lots of shops!

**Comment by Sentropic** [comment]
Already implemented by putting `SearchSubfoldersForShops: true` in the config

**Comment by leogianfagna** [comment]
> Already implemented by putting `SearchSubfoldersForShops: true` in the config

@Sentropic thanks so much for this <3
