### ISSUE TITLE
customskull warning

### ISSUE THREAD

**Issue by HYDeath** [promcteam/BossShopPro#45]
Kernel: paper-1.20.2-297
Using customskull in the menu opens the menu with the following warning:
WARN. 
Found inconsistent skull meta, this should normally not happen and is not a Bukkit / Spigot issue, but one from a plugin you are using.
Bukkit will attempt to fix it this time for you, but may not be able to do this every time.
If you see this message after typing a command from a plugin, please report this to the plugin developer, they should use the api instead of relying on reflection (and doing it the wrong way).

Translated with www.DeepL.com/Translator (free version)

**Comment by Travja** [comment]
I am aware of this. Due to time constraints, I haven't bothered to figure out exactly why this error is being thrown. For now, it shouldn't be an issue, however.

**Comment by goflishMC** [comment]
This has been fixed in the latest dev builds.
