### ISSUE TITLE
I use Gringotts which uses vault but the shop doesn't recognize it as currency.

### ISSUE THREAD

**Issue by rackgaming** [promcteam/BossShopPro#5]
so basically I wanted to ask if this https://www.spigotmc.org/resources/gringotts.42071/ could be integrated as a supported vault currency(I love their system), because it works with LevelledMobs whenever the mob is killed, the gringotts are emeralds and with emeralds they become money through vault & so far only works with ShopKeepers.

**Comment by lijinhong11** [comment]
Added in version 2.1.0-SNAPSHOT
