### ISSUE TITLE
Main.OpenShop and Main.CloseShop messages

### ISSUE THREAD

**Issue by SuzuGames** [promcteam/BossShopPro#59]
Every time I open a menu of the plugin it sends me the following messages, is there a way to deactivate them?
![image](https://github.com/promcteam/BossShopPro/assets/79166566/d27cc8be-2934-497b-8279-eb0fab5b6bf4)

**Comment by Travja** [comment]
It should be sourcing those from your Lang file

**Comment by SuzuGames** [comment]
I already found the problem, I changed the language to es-es but apparently the plugin did not install that translation, I already installed it manually, thank you very much ^^
