### ISSUE TITLE
Suggestion for another type of economy

### ISSUE THREAD

**Issue by LordYarkan** [promcteam/BossShopPro#60]
Hello
I thought this plugin had ceased to exist, thanks for updating it!

Could you add compatibility with the V-MultiEconomies plugin please?
plugin: https://www.spigotmc.org/resources/v-multieconomies-multiple-customizable-economies-1-8-1-19.105322/

have a nice day
:)

**Comment by Travja** [comment]
It would be up to them to integrate properly with Vault. Once they integrate with Vault, you'd have your integration.
